---
- name: debug
  debug:
    msg: "Jeste postfixe standalone"
- block:
    - name: install postfix
      yum:
        name:
          - postfix
          - cyrus-sasl-plain
        state: installed

    - name: install postfix-ldap on rhel 8
      yum:
        name:
          - postfix-ldap
        state: installed
      when: ansible_distribution_major_version == "8"

    - name: get postfix user info
      getent:
        database: passwd
        key: postfix
    - name: set _postfix_user variable
      set_fact:
        _postfix_user: "{{ getent_passwd['postfix'] }}"

    - block:
        - name: create vmaildir
          file:
            path: "/var/lib/vmail/{{ item }}"
            state: directory
            owner: postfix
            group: postfix
            mode: 0700
            # setype: postfix_virtual_t
            setype: mail_spool_t
          loop: "{{ app.value.postfix.configs.vmailbox.domains|default({})|list }}"
        - name: create db dir
          file:
            path: /etc/postfix/db
            state: directory
            owner: root
            group: root
            mode: 0755
        - name: create virtual mailboxes
          template:
            dest: "/etc/postfix/db/{{ domain.key }}.hash"
            src: "vmailbox"
            owner: root
            group: root
            mode: 0755
          loop: "{{ app.value.postfix.configs.vmailbox.domains|default({})|dict2items }}"
          loop_control:
            loop_var: domain
          notify: postmap
        - name: create aliases
          template:
            dest: "/etc/postfix/db/alias_{{ domain.key }}.hash"
            src: "virtual"
            owner: root
            group: root
            mode: 0755
          loop: "{{ app.value.postfix.configs.vmailbox.domains|default({})|dict2items }}"
          loop_control:
            loop_var: domain
          when: domain.value.aliases | default(False)
          notify: postmap

        - name: create virtual mailboxes ldap
          template:
            dest: "/etc/postfix/db/ldap_{{ ldap.key }}.cf"
            src: "vmailbox_ldap"
            owner: root
            group: root
            mode: 0755
          loop: "{{ app.value.postfix.configs.ldap|default({})|dict2items }}"
          loop_control:
            loop_var: ldap
          notify: postmap
        - name: copy sasl2/smtpd.conf
          template:
            dest: /etc/sasl2/smtpd.conf
            src: sasl2_smtpd.conf
            owner: root
            group: root
            mode: 0644
        - name: create local users
          vars:
            _domains: "{{ apps_postfix.postfix.postfix.configs.vmailbox.domains|dict2items }}"
          sasluser:
            username: "{{ user.1.username }}@{{ user.0.key }}"
            password: "{{ user.1.password }}"
          loop: "{{ q('subelements', _domains, 'value.users', {'skip_missing': True}) }}"
          loop_control:
            loop_var: user
          when: user.1.password|default(False)

        - name: stat sasldb2
          stat:
            path: /etc/sasldb2
          register: _sasldb2

        - name: set sasldb permissions
          file:
            state: file
            path: /etc/sasldb2
            owner: postfix
            group: postfix
          when: _sasldb2.stat.exists

      when: app.value.postfix.configs.vmailbox|default(False)
    - meta: flush_handlers

    - name: copy config
      template:
        src: main.cf
        dest: /etc/postfix/main.cf
        mode: 0640
      notify:
        - restart postfix
    - meta: flush_handlers
    - name: start and enable postfix
      service:
        name: postfix
        state: started
        enabled: true
  become: true
  become_user: root
